
#service_type: FilterJointTrajectoryWithConstraints
#filter_chain:
#  -
#    name: parabolic_blend_shortcutter
#    type: ParabolicBlendShortCutterFilterJointTrajectoryWithConstraints
#    params: {discretization: 0.01, num_iterations: 10}
#

service_type: FilterJointTrajectoryWithConstraints
filter_chain:
  -
    name: unnormalize_trajectory
    type: UnNormalizeFilterJointTrajectoryWithConstraints
  -
    name: iterative_parabolic_smoother
    type: IterativeParabolicSmootherFilterJointTrajectoryWithConstraints
    params: {max_iterations: 100, max_time_change_per_it: 0.01}
          
